"""empty message

Revision ID: 9a14c4b97ab7
Revises: 
Create Date: 2018-12-28 22:11:03.619494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a14c4b97ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'user_id')
    # ### end Alembic commands ###
